summary: incorrect error reporting after stack overflow
reported: Panagiotis Vossos <jacbre@internet.gr>, 2002-02-19

Panagiotis Vossos sez:

I have guile 1.5.4 installed and I discovered something strange.

guile> (define (foo n) (+ n (foo n)))
guile> (foo 10)
ERROR: Stack overflow
ABORT: (stack-overflow)
guile> thisisabug
<unnamed port>: In expression thisisabug:
<unnamed port>: Unbound variable: thisisabug
ABORT: (unbound-variable)
guile> (foo 10)
<unnamed port>: In expression thisisabug:
<unnamed port>: Stack overflow
ABORT: (stack-overflow)

The last message shows the previous unbound variable 'thisisabug'.
'foo' is just an example, this seems to happen for every function that
causes overflow.  It's not serious, but it sure looks misleading..

Neil Jerram sez:

It's something to do with the way that debug info frames cope with
stack overflow.
